apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventrouter.fullname" . }}
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "sink": "{{ .Values.sink }}"
    }
